### ISSUE TITLE
bower install/update error

### ISSUE THREAD

**Issue by TheAliAbbasi** [wvega/timepicker#81] opened 2016-07-09 06:25 UTC
it's not possible to install version 1.3.4 because of some problems in bower.json
bower shows "unexpected ]"

**Comment by wvega** [comment] 2016-07-10 05:03
@TheAliAbbasi thanks for reporting this problem. The issue was caused by an stray comma in `bower.json` and was fixed with this PR: https://github.com/wvega/timepicker/pull/80.

I just released a new version (1.3.5) that includes that modification. You should be able to install jQuery Timepicker 1.3.5 without problems.

``` bash
$ bower install jquery-timepicker-wvega#1.3.4
bower jquery-timepicker-wvega#1.3.4       not-cached https://github.com/wvega/timepicker.git#1.3.4
bower jquery-timepicker-wvega#1.3.4          resolve https://github.com/wvega/timepicker.git#1.3.4
bower jquery-timepicker-wvega#1.3.4         checkout 1.3.4
bower jquery-timepicker-wvega#1.3.4       EMALFORMED Failed to read /var/folders/_x/tp_2f5b107x2_yg8gfpd43700000gn/T/wvega/bower/95b171ea434b185b0727b3dddb9a1635-33646-UYcXUA/bower.json

Additional error details:
Unexpected token ]
```

``` bash
$ bower install jquery-timepicker-wvega#1.3.5
bower jquery-timepicker-wvega#1.3.5           cached https://github.com/wvega/timepicker.git#1.3.5
bower jquery-timepicker-wvega#1.3.5         validate 1.3.5 against https://github.com/wvega/timepicker.git#1.3.5
bower jquery#>= 1.4.3                         cached https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery#>= 1.4.3                       validate 3.1.0 against https://github.com/jquery/jquery-dist.git#>= 1.4.3
bower jquery-timepicker-wvega#1.3.5          install jquery-timepicker-wvega#1.3.5
bower jquery#>= 1.4.3                        install jquery#3.1.0

jquery-timepicker-wvega#1.3.5 bower_components/jquery-timepicker-wvega
└── jquery#3.1.0

jquery#3.1.0 bower_components/jquery
```

**Closed by wvega** 2016-07-10 05:03 UTC
Labels: bug
